# Generated by Django 5.0.7 on 2024-11-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=30)),
                ('car_type', models.CharField(max_length=30)),
                ('km_run', models.IntegerField()),
                ('mfg_year', models.IntegerField()),
                ('car_img', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('no_of_seats', models.IntegerField()),
                ('engine_type', models.CharField(max_length=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact', models.CharField(max_length=15)),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=15)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=15)),
                ('color', models.CharField(max_length=20)),
                ('registration_state', models.CharField(max_length=30)),
                ('owner_count', models.IntegerField(help_text='Number of previous owners')),
                ('insurance_validity', models.DateField(blank=True, help_text='Expiry date of insurance', null=True)),
                ('last_service_date', models.DateField(blank=True, help_text='Last service date', null=True)),
                ('description', models.TextField(blank=True, help_text='Additional details about the car condition, features, etc.', null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Mark if this is a featured listing')),
                ('is_sold', models.BooleanField(default=False, help_text='Mark if the car is sold')),
            ],
        ),
    ]
